site_name: Mod Tool Documentation
site_url: https://oleg52.github.io/ModToolDocs
theme:
  name: material
  favicon: assets/images/favicon.ico
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search

nav:
  - Home: index.md
  - Global Options:
    - Dev Mode: global/dev-mode.md
    - Precise Templates: global/precise-templates.md
    - Skip Race Testing: global/skip-test.md
    - Test Race: global/test-race.md
    - Save Map: global/save-map.md
    - Publish Map: global/publish-map.md
  - Props:
    - Overview: props/overview.md
    - Blacklisted Props: props/blacklist.md
    - Advanced Restore: props/advanced-restore.md
    - Auto Placement:
      - Overview: props/auto-placement/overview.md
      - Numbers: props/auto-placement/numbers.md
      - Stairs & Spiral: props/auto-placement/strairs-spiral.md
      - Props List: props/auto-placement/props-list.md
  - Checkpoints:
    - Points: checkpoints/points/overview.md
    - Vehicles:
      - Overview: checkpoints/vehicles/overview.md
      - Grid Vehicles Presets: checkpoints/vehicles/presets.md
  - Race Settings:
    - Map Options: race-settings/map-options/overview.md
    - Vehicles: race-settings/vehicles/overview.md
    - Locations: race-settings/locations/overview.md
    - Online Options: race-settings/online-options/overview.md
    - menubs: race-settings/menubs/overview.md
  - Addons:
    - Zones: addons/zones/overview.md
    - Fixtures: addons/fixtures/overview.md
    - Units: addons/units/overview.md
  - Stuff: stuff/overview.md
  - Prop Swap:
    - Models: prop-swap/models/overview.md
    - Textures: prop-swap/textures/overview.md
  - Hidden Jobs: hidden-jobs/overview.md
  - Copy Tool:
    - Copy: copy-tool/copy/overview.md
    - Options: copy-tool/options/overview.md
    - Jobs Replacement: copy-tool/jobs-replacement/overview.md
  - Tips:
    - Disable BE: tips/disable-be.md
    - Arrow Control: tips/arrow-control.md
    - Add/Delete: tips/add-delete.md
    - Range Formats: tips/range-formats.md